name: "guoyz-android-build-scan"
on: push

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform URL (for example: https://artifactory_url)
          JF_URL: ${{ vars.JF_URL }}
          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          # Need to add the users, or the publish will report 401
          JF_USER: ${{ secrets.JF_USER }}
        with:
          # Name of the OIDC provider as specified on the OIDC integration page in the JFrog Platform
          oidc-provider-name: guoyz-github

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 
        with:
          gradle-version: '7.6.3'
          # Solve the error "Error: At least one Gradle Wrapper Jar failed validation!"
          validate-wrappers: false

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping  
          # Set up Gradle configuration
          jf gradle-config --server-id-resolve=setup-jfrog-cli-server --repo-resolve=guoyz-maven-virtual --server-id-deploy=setup-jfrog-cli-server --repo-deploy=guoyz-maven-dev-local
          # Gradle(Android) Build
          jf gradle clean assembleRelease artifactoryPublish
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
          # Android build scan
          jf bs guoyz-android-build-scan ${{ github.run_number }} --fail=false
